### ISSUE TITLE
Omega Arduino Dock Schematics

### ISSUE THREAD

**Issue by feilipu** [OnionIoT/Onion-Hardware#1]
Would like to have the Omega Arduino Dock Schematics available too, please.

**Comment by feilipu** [comment]
Bump!

**Comment by ChengyenYen** [comment]
Hope arduino dock schematics can be released  too, please.

**Comment by feilipu** [comment]
Is there an issue as to why the Arduino Dock schematics can't be released?
Please get them out.

**Comment by feilipu** [comment]
Bump... schematics, please.

**Comment by feilipu** [comment]
Thanks.

Please close issue.
