### ISSUE TITLE
Schematics for Omega2 Pro? emmc?

### ISSUE THREAD

**Issue by tonytee** [OnionIoT/Onion-Hardware#8]
Hi,

Any chance on schematics for the Pro? We are in the process of incorporating Omega2s in our product design, and we'd like to know how to connect emmc to 2s... dev kit is not completely clear on that so we were kind of curious how you did that on the Pro

we can't figure out why (and if) you really need pin gpio18..21 / dat4..7 for emmc... we are looking to connect only 4 or 8G

Thanks, Tony

**Comment by greenbreakfast** [comment]
Please see: https://github.com/OnionIoT/omega2-pro

**Comment by tonytee** [comment]
sorry for missing that one... thanks for pointing it out... grtzT
